spring.application.name=rpg
spring:
    datasource:
    url: jdbc:postgresql://dpg-csloa99u0jms73fa6j8g-a.oregon-postgres.render.com/rpgauth?user=rpgauth_user&password=fasq2XDK20Q1QGEMEWTlIRhMBionCIcw
    username: rpgauth_user
    password: fasq2XDK20Q1QGEMEWTlIRhMBionCIcw
    driver-class-name: org.postgresql.Driver
jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: none
        show-sql: true