spring.application.name=rpg
spring.datasource.url=jdbc:postgresql://dpg-csloa99u0jms73fa6j8g-a.oregon-postgres.render.com/rpgauth?user=rpgauth_user&password=fasq2XDK20Q1QGEMEWTlIRhMBionCIcw
spring.datasource.username=rpgauth_user
spring.datasource.password=fasq2XDK20Q1QGEMEWTlIRhMBionCIcw
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.security.jwt.token.secret-key=secret